filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

filebeat.inputs:
  - type: log
    enabled: true
    fields_under_root: true
    fields:
      type: app
    paths:
      - /logs/*/*.log

  - type: container
    enabled: true
    fields_under_root: true
    fields:
      type: container
    paths:
      - "/var/lib/docker/containers/*/*.log"

output.logstash:
  hosts: ["logstash:5044"]
